export type { IPropsElements } from './IPropsElements'
export type { IOpenFile } from './IOpenFile'
export type { ISubMenuObj } from './ISubMenuPages'
export type { IProfileInfoSubPages, IProjectsSubPages, IContactSubPages } from './ISubPages'
export type { IErrorInputsState, IInputsData, IName, IHasError } from './IFormErrorInputs'
export type { IIsExpandedProject } from './IIsExpanedProject'
export type { IPreviousProjectObj, IImages } from './IPreviousProjectObj'
